openapi: "3.0.0"
info:
  title: TOMATO Timer Document
  version: "0.0.1"
  description: トマトなAPIのドキュメントだよ～ん。🍅
tags:
  - name: tomato
    description: ポモドーロタイマ関連のAPI
paths:
  /tomato/v1/createTimer:
    post:
      summary: "ポモドーロタイマ作成"
      description: "タイマーを新規作成します。"
      operationId: "createTimer"
      tags:
        - tomato
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTimerForm"
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTimerDTO"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestErrorDTO"
components:
  schemas:
    CreateTimerForm:
      type: object
      properties:
        workDuration:
          type: integer
          description: "作業時間"
        breakDuration:
          type: integer
          description: "休憩時間"
        totalSetCount:
          type: integer
          description: "トータルセット数"
      example:
        workDuration: 15
        breakDuration: 5
        totalSetCount: 3
      required:
        - workDuration
        - breakDuration
        - totalSetCount
    CreateTimerFormDTO:
      allOf:
        - $ref: "#/components/schemas/CreateTimerForm"
    CreateTimerDTO:
      type: object
      properties:
        timerId:
          type: string
          description: "タイマーID"
        setList:
          type: array
          description: "セットリスト"
          items:
            $ref: "#/components/schemas/SetDetail"
      example:
        timerId: 1
        setList:
          - currentSetCount: 1
            startWorkTime: "2024/07/30 21:15:00"
            endWorkTime: "2024/07/30 21:15:00"
            endBreakTime: "2024/07/30 21:20:00"
          - currentSetCount: 2
            startWorkTime: "2024/07/30 21:20:00"
            endWorkTime: "2024/07/30 21:35:00"
            endBreakTime: "2024/07/30 21:40:00"
          - currentSetCount: 3
            startWorkTime: "2024/07/30 21:40:00"
            endWorkTime: "2024/07/30 21:55:00"
            endBreakTime: "2024/07/30 22:00:00"
      required:
        - timerId
        - startWorkTime
        - endWorkTime
        - endBreakTime
    BadRequestErrorDTO:
      description: "リクエストが不正です"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイトル"
        detail:
          type: string
          description: "エラーの詳細"
        status:
          type: string
          description: "ステータス"
        invalidParams:
          type: array
          items:
            $ref: "#/components/schemas/InvaildDetail"
      required:
        - title
        - detail
        - status
        - invalidParams
      example:
        title: "Bad Request"
        detail: "作業時間は必須です。"
        status: "404"
        invalidParams:
          - name: "workDuration"
            reason: "値が欠落しています"
    InvaildDetail:
      description: "不正なリクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: "エラーが発生したフィールド名"
        reason:
          type: string
          description: "エラーの理由"
      required:
        - name
        - reason
    SetDetail:
      type: object
      properties:
        currentSetCount:
          type: integer
          description: "現在のセット数"
        startWorkDatetime:
          type: string
          description: "作業開始日時分秒"
        endWorkDatetime:
          type: string
          description: "作業終了日時分秒"
        endBreakDatetime:
          type: string
          description: "休憩終了日時分秒"
        statusTypeCode:
          type: string
          description: "ステータス"
    TimerInformationEntity:
      type: object
      properties:
        timerId:
          type: string
          description: "タイマーID"
        currentSetCount:
          type: integer
          description: "現在のセット数"
        totalSetCount:
          type: integer
          description: "トータルセット数"
        startWorkDatetime:
          type: string
          description: "作業開始日時分秒"
        endWorkDatetime:
          type: string
          description: "終了開始日時分秒"
        endBreakDatetime:
          type: string
          description: "休憩終了日時分秒"
        statusTypeCode:
          type: string
          description: "ステータス"
        insertDatetime:
          type: string
          description: "登録日時分秒"
        insertFunction:
          type: string
          description: "登録機能"
        updateDatetime:
          type: string
          description: "更新日時分秒"
        updateFunction:
          type: string
          description: "更新機能"
        updateCount:
          type: integer
          description: "更新回数"
